/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ASpace: typeof import('ant-design-vue/es')['Space']
    CopyText: typeof import('./../src/components/copy-text/index.vue')['default']
    DashboardIndex: typeof import('./../src/views/dashboard/DashboardIndex.vue')['default']
    LoginIndex: typeof import('./../src/views/login/LoginIndex.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeCopyText: typeof import('./../src/components/se-copy-text/index.vue')['default']
    SeSvgIcon: typeof import('./../src/components/se-svg-icon/index.vue')['default']
    SvgIcon: typeof import('./../src/components/svg-icon/index.vue')['default']
    UpdatePwa: typeof import('./../src/views/update-pwa/index.vue')['default']
  }
}
